[Enhancement] Support Prompt-to-prompt, ddim inversion and null-text inversion
open-mmlab/mmagic pull request #1908
Opened 2023-06-17 07:56 UTC by FerryHuang

Support Prompt-to-prompt, ddim inversion and null-text inversion.

Considering that these three methods share common features and can be combined, I implemented them as modules in this project.

## Checklist

**Before PR**:

- [√] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) to create this PR.
- [√] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [√] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [√] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [√] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-06-27 08:38 UTC, LeoXing1996 requested changes

2023-06-27 08:38 UTC, LeoXing1996 commented on projects/prompt_to_prompt/inversions/ddim_inversion.py
> +        self.model.schdueler = scheduler
`schdueler` -> `scheduler`

2023-06-27 12:29 UTC, FerryHuang commented on projects/prompt_to_prompt/inversions/ddim_inversion.py
> +    def init_prompt(self, prompt: str):
Thanks for your feedback and kind suggestion! This implementation intends to use text prompt as additional information to get the noise prediction so as to guide the inversion process to be more precise. I implement it with reference to the ddim inversion part of the original null-text inversion paper.
![image](https://github.com/open-mmlab/mmagic/assets/71176040/9bda3c45-8285-45e6-a5db-71cc9d062544)
The _C_ here is likely to be the text prompt and it's actually the classifier-free guidance under the case of w=1, (the _pivot _pivot_ named by the author). So I vote for keeping it here for use in both inversions.

2023-07-11 10:59 UTC, LeoXing1996 commented
@FerryHuang Sorry for late response. The implementation is already good enough. However, there is one aspect that needs improvement: directly uploading images will increase the repository's size. Please change the images in the markdown to image hosting links. 

For example, you can drag and drop an image into the chat box in Github and a link will be generated. This link will be permanently saved in Github and you can use it in your markdown.

2023-07-11 13:28 UTC, FerryHuang commented
> @FerryHuang Sorry for late response. The implementation is already good enough. However, there is one aspect that needs improvement: directly uploading images will increase the repository's size. Please change the images in the markdown to image hosting links.
> 
> For example, you can drag and drop an image into the chat box in Github and a link will be generated. This link will be permanently saved in Github and you can use it in your markdown.

Thanks for the trick! And changes have been made~

2023-07-12 02:21 UTC, LeoXing1996 approved these changes
LGTM! Great work!

2023-07-12 02:22 UTC, merged