Translate models.md's en version into chinese
open-mmlab/mmagic pull request #1934
Opened 2023-07-11 12:27 UTC by wslgqq277g

translation work has been done, please check it.

2023-07-11 12:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmagic?pullRequest=1934) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmagic?pullRequest=1934) before we can accept your contribution.<br/><hr/>**wslgqq277g** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmagic?pullRequest=1934) it.</sub>

2023-07-11 17:47 UTC, zengyh1900 requested changes
Thanks for your contribution! It looks good to me!
I have suggested several changes to make it better. After the change, we can merge this pull request.

2023-07-11 17:47 UTC, zengyh1900 commented on docs/zh_cn/migration/models.md
> +MMagic 1.x 中的 models 被重构为六个部分：archs、base_models、data_preprocessors、editors、diffusion_schedulers 和 losses。
```suggestion
- MMagic 1.x 中的 `models` 被重构为六个部分：`archs`、`base_models`、`data_preprocessors`、editors、`diffusion_schedulers` 和 `losses`。
```

2023-07-11 17:47 UTC, zengyh1900 commented on docs/zh_cn/migration/models.md
> +在 models 中添加了 data_preprocessor 模块。归一化和颜色空间转换操作从 dataset transform 流程中移动到 data_preprocessor 中。数据流从数据管道中输出后，先经过 data_preprocessor 模块的转换，然后再输入模型中。
```suggestion
- 在 `models` 中添加了 `data_preprocessor` 模块。这里主要是将归一化和颜色空间转换操作从 `dataset transform` 流程中移动到 `data_preprocessor` 中。此时，数据流经过数据预处理后，会先经过 `data_preprocessor` 模块的转换，然后再输入到模型中。
```

2023-07-12 01:48 UTC, wslgqq277g commented on docs/zh_cn/migration/models.md
> +- 添加 `data_preprocessor` 字段. 归一化和颜色空间变换操作从datasets transforms流程中转到data_preprocessor.我们接下来会介绍data_preprocessor。
- 添加 `data_preprocessor` 字段. 归一化和颜色空间变换操作从datasets transforms流程中转到data_preprocessor.我们接下来会介绍data_preprocessor。
+-- 添加 `data_preprocessor` 字段. 这里主要是将归一化和颜色空间转换操作从 `dataset transform` 流程中移动到 `data_preprocessor` 中.我们接下来会介绍`data_preprocessor`.

2023-07-12 02:11 UTC, zengyh1900 commented on docs/zh_cn/migration/models.md
> +- 添加 `data_preprocessor` 字段. 归一化和颜色空间变换操作从datasets transforms流程中转到data_preprocessor.我们接下来会介绍data_preprocessor。
hi，现在文档部分似乎没有修改过来，你需要再修改一下。

2023-07-12 02:12 UTC, zengyh1900 commented on docs/zh_cn/migration/models.md
> +- 添加 `data_preprocessor` 字段. 归一化和颜色空间变换操作从datasets transforms流程中转到data_preprocessor.我们接下来会介绍data_preprocessor。
另外， 可以参考 https://mmagic.readthedocs.io/zh_CN/latest/community/contributing.html#id13 ，通过 pre-commit 来修正 lint（代码风格）的问题

2023-07-12 07:49 UTC, zengyh1900 approved these changes
lgtm.

2023-07-12 07:49 UTC, merged

2023-07-18 11:06 UTC, OpenMMLab-Assistant-004 commented
Hi @wslgqq277g,

We'd like to express our appreciation for your valuable contributions to the mmagic. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!